# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 2
Lint/HandleExceptions:
  Enabled: false

# Offense count: 74
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 30
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 22
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Offense count: 349
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false
