
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 112

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false
